### ISSUE TITLE
 can you provide the steps for install this plugin?

### ISSUE THREAD

**Issue by panteliskopsias** [Jitheesh/Magento2-configurable#1]

**Comment by Jitheesh** [comment]
Please note, I didn't tested this extension on recent Magento 2 versions.

Installation steps:

- Download files
- Copy 'Jworks' Directory into app/code
- Enter the following at the command line
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy
